using System;
using System.IO;
using Aspose.Email;

class Program
{
    static void Main()
    {
        try
        {
            // Input EML file path
            string inputPath = "sample.eml";

            // Ensure the input file exists; create a minimal placeholder if missing
            if (!File.Exists(inputPath))
            {
                using (FileStream placeholderStream = new FileStream(inputPath, FileMode.Create, FileAccess.Write))
                {
                    using (MailMessage placeholderMessage = new MailMessage())
                    {
                        placeholderMessage.From = new MailAddress("sender@example.com");
                        placeholderMessage.To.Add(new MailAddress("receiver@example.com"));
                        placeholderMessage.Subject = "Placeholder Email";
                        placeholderMessage.Body = "This is a placeholder email generated by the sample.";
                        placeholderMessage.Save(placeholderStream);
                    }
                }
            }

            // Load the email message
            using (MailMessage message = MailMessage.Load(inputPath))
            {
                // Save as EML using default options
                string emlOutput = "output.eml";
                message.Save(emlOutput, SaveOptions.DefaultEml);

                // Save as MSG (Unicode) using MsgSaveOptions
                string msgOutput = "output.msg";
                MsgSaveOptions msgOptions = new MsgSaveOptions(MailMessageSaveType.OutlookMessageFormatUnicode);
                message.Save(msgOutput, msgOptions);

                // Save as MHTML using default options
                string mhtmlOutput = "output.mhtml";
                message.Save(mhtmlOutput, SaveOptions.DefaultMhtml);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("Error: " + ex.Message);
        }
    }
}