using System;
using System.IO;
using Aspose.Email;

class Program
{
    static void Main()
    {
        try
        {
            // Define the folder containing email files
            string folderPath = "Emails";

            // Ensure the folder exists
            if (!Directory.Exists(folderPath))
            {
                try
                {
                    Directory.CreateDirectory(folderPath);
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine($"Error: Unable to create directory – {folderPath}. {ex.Message}");
                    return;
                }
            }

            // Create a minimal placeholder EML file if the folder is empty
            string[] existingFiles = Directory.GetFiles(folderPath, "*.eml");
            if (existingFiles.Length == 0)
            {
                string placeholderPath = Path.Combine(folderPath, "placeholder.eml");
                try
                {
                    using (StreamWriter writer = new StreamWriter(placeholderPath, false))
                    {
                        writer.WriteLine("From: placeholder@example.com");
                        writer.WriteLine("To: recipient@example.com");
                        writer.WriteLine("Subject: Placeholder Email");
                        writer.WriteLine();
                        writer.WriteLine("This is a placeholder email generated by the sample.");
                    }
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine($"Error: Unable to write placeholder file – {placeholderPath}. {ex.Message}");
                    return;
                }
                existingFiles = new string[] { placeholderPath };
            }

            // Iterate through the files using a foreach loop (alternative to a for loop)
            foreach (string filePath in existingFiles)
            {
                // Guard against missing files
                if (!File.Exists(filePath))
                {
                try
                {
                    using (MailMessage placeholder = new MailMessage(
                        "sender@example.com",
                        "recipient@example.com",
                        "Placeholder Subject",
                        "Placeholder body."))
                    {
                        placeholder.Save(filePath, SaveOptions.DefaultEml);
                    }
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine($"Error creating placeholder message: {ex.Message}");
                    return;
                }

                    Console.Error.WriteLine($"Warning: File not found – {filePath}");
                    continue;
                }

                // Load the email message and display its subject
                try
                {
                    using (MailMessage message = MailMessage.Load(filePath))
                    {
                        Console.WriteLine($"Loaded '{Path.GetFileName(filePath)}' – Subject: {message.Subject}");
                    }
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine($"Error: Failed to load message from '{filePath}'. {ex.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Unhandled exception: {ex.Message}");
        }
    }
}
