using System;
using System.IO;
using Aspose.Email;

class Program
{
    static void Main()
    {
        try
        {
            // Define output directory and file path
            string outputDirectory = "Output";
            string outputFilePath = Path.Combine(outputDirectory, "AutoGeneratedEmail.eml");

            // Ensure the output directory exists
            if (!Directory.Exists(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            // Create the email message
            using (MailMessage message = new MailMessage("sender@example.com", "recipient@example.com", "Test Email", "This is a test email."))
            {
                // Add an auto-generated header
                message.Headers["X-Auto-Generated"] = "This email was created automatically by a system.";

                // Save the message to a file with error handling
                try
                {
                    message.Save(outputFilePath);
                    Console.WriteLine($"Email saved to: {outputFilePath}");
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine($"Failed to save email: {ex.Message}");
                    return;
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}
