using System;
using System.IO;
using Aspose.Email;

namespace AsposeEmailRuleExample
{
    // Represents a simple rule with a condition and an associated action.
    public class Rule
    {
        // Predicate that determines whether the rule applies to a given MailMessage.
        public Func<MailMessage, bool> Condition { get; set; }

        // Action to execute when the condition is satisfied.
        public Action<MailMessage> Action { get; set; }

        // Evaluates the condition and executes the action if applicable.
        public void Evaluate(MailMessage message)
        {
            if (this.Condition != null && this.Condition(message))
            {
                if (this.Action != null)
                {
                    this.Action(message);
                }
            }
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            try
            {
                // Define the path to the sample EML file.
                string emlPath = "sample.eml";

                // Ensure the file exists; create a minimal placeholder if missing.
                if (!File.Exists(emlPath))
                {
                    try
                    {
                        using (FileStream fs = new FileStream(emlPath, FileMode.Create, FileAccess.Write))
                        using (StreamWriter writer = new StreamWriter(fs))
                        {
                            writer.WriteLine("From: sender@example.com");
                            writer.WriteLine("To: recipient@example.com");
                            writer.WriteLine("Subject: Test Email");
                            writer.WriteLine();
                            writer.WriteLine("This is a placeholder email generated by the example.");
                        }
                    }
                    catch (Exception ioEx)
                    {
                        Console.Error.WriteLine("Failed to create placeholder EML file: " + ioEx.Message);
                        return;
                    }
                }

                // Load the email message from the file.
                using (MailMessage message = MailMessage.Load(emlPath))
                {
                    // Create and configure a new rule instance.
                    Rule rule = new Rule();

                    // Conditional logic: trigger when the subject contains the word "Test".
                    rule.Condition = delegate (MailMessage msg)
                    {
                        return !string.IsNullOrEmpty(msg.Subject) && msg.Subject.Contains("Test");
                    };

                    // Associated action: write details to the console.
                    rule.Action = delegate (MailMessage msg)
                    {
                        Console.WriteLine("Rule triggered for message:");
                        Console.WriteLine("Subject: " + msg.Subject);
                        Console.WriteLine("From: " + msg.From);
                        Console.WriteLine("To: " + msg.To);
                    };

                    // Evaluate the rule against the loaded message.
                    rule.Evaluate(message);
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("An error occurred: " + ex.Message);
            }
        }
    }
}