using System;
using System.IO;
using Aspose.Email;
using Aspose.Email.Clients.Exchange;
using Aspose.Email.Clients.Exchange.WebService;

class Program
{
    static void Main()
    {
        try
        {
            // Path for the log file generated by EWSClient
            string logFilePath = "ews_log.txt";

            // Ensure any previous log file is removed
            if (File.Exists(logFilePath))
            {
                File.Delete(logFilePath);
            }

            // Initialize the EWS client (replace with actual service URL and credentials)
            string mailboxUri = "https://example.com/EWS/Exchange.asmx";
            string username = "username";
            string password = "password";

            // Skip external calls when placeholder credentials are used
            if (mailboxUri.Contains("example.com") || username == "username" || password == "password")
            {
                Console.Error.WriteLine("Placeholder credentials detected. Skipping external calls.");
                return;
            }

            IEWSClient ewsClient = EWSClient.GetEWSClient(mailboxUri, username, password);

            // Assign the log file name so that the client writes diagnostic information
            ewsClient.LogFileName = logFilePath;

            // Perform a simple operation to generate log entries
            try
            {
                ExchangeMailboxInfo mailboxInfo = ewsClient.GetMailboxInfo();
                Console.WriteLine("Mailbox URI: " + mailboxInfo.MailboxUri);
            }
            catch (Exception operationEx)
            {
                Console.Error.WriteLine("EWS operation failed: " + operationEx.Message);
            }

            // Dispose the client if it implements IDisposable
            if (ewsClient is IDisposable disposableClient)
            {
                disposableClient.Dispose();
            }

            // Read and display the log content if the file was created
            if (File.Exists(logFilePath))
            {
                try
                {
                    string[] logLines = File.ReadAllLines(logFilePath);
                    Console.WriteLine("=== EWS Log Output ===");
                    foreach (string line in logLines)
                    {
                        Console.WriteLine(line);
                    }
                }
                catch (Exception readEx)
                {
                    Console.Error.WriteLine("Failed to read log file: " + readEx.Message);
                }
            }
            else
            {
                Console.Error.WriteLine("Log file was not created.");
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("Unexpected error: " + ex.Message);
        }
    }
}
