using Aspose.Email.Clients.Exchange.WebService;
using System;
using System.Net;
using Aspose.Email;
class Program
{
    static void Main()
    {
        try
        {
            // Prepare the mail message
            MailMessage message = new MailMessage();
            message.From = "no-reply@example.com";
            message.To.Add("user@example.com");
            message.Subject = "Automated Notification";
            message.Body = "This is an automated notification generated by the system.";
            // Set importance to High via standard header
            message.Headers.Add("Importance", "High");
            // Optionally set X-Priority for compatibility
            message.Headers.Add("X-Priority", "1");

            // Create and configure the Exchange client (WebDAV)
            // Replace with actual mailbox URI and credentials
            string mailboxUri = "https://exchange.example.com/EWS/Exchange.asmx";

            // Skip external calls when placeholder credentials are used
            if (mailboxUri.Contains("example.com"))
            {
                Console.Error.WriteLine("Placeholder credentials detected. Skipping external calls.");
                return;
            }

            NetworkCredential credentials = new NetworkCredential("username", "password");

            using (IEWSClient client = EWSClient.GetEWSClient(mailboxUri, credentials))
            {
                try
                {
                    client.Send(message);
                    Console.WriteLine("Message sent successfully with High importance.");
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine($"Failed to send message: {ex.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Unexpected error: {ex.Message}");
        }
    }
}
